# Generated by Django 4.0.4 on 2022-05-25 01:02

import cpf_field.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('data_nascimento', models.DateField()),
                ('hora', models.TimeField()),
                ('genero', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=50)),
                ('gol', models.BooleanField(default=False)),
            ],
        ),
    ]
